language: python
python:
  - "3.7"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run py.test -vvra --tb=native --cov-report=term-missing --cov=admanifest tests
  - poetry run admanifest-check
