language: python
python:
  - "3.6"
env:
  - PATH=$HOME/.poetry/bin:$PATH
before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
install:
  - poetry install
script:
  - poetry run py.test -vvra --tb=native --cov-report=term-missing --cov=admanifest tests
  - poetry run admanifest-check
