---
$schema: http://json-schema.org/draft-04/schema#
title: Data needed for a project
description: >
  Data description containing information about data needed for a project.
type: object
properties:
  id:
    type: string
    title: Project ID
    description: >
      Unique idetifier for a project withing a repository where all data
      descriptions are stored..
  title:
    type: string
    title: Project name
  type:
    enum:
      - project
  impact:
    type: array
    title: List of impact indicators by year
    items:
      $ref: "#/definitions/impact"
  since:
    type: string
    format: date
  until:
    type: string
    format: date
  objects:
    type: object
    title: Data description
    patternProperties:
      "^[a-zA-Z_]+$":
        type: object
        title: Data object
        properties:
          source:
            type: string
            title: Data source
            description: >
              ID of data source.
          since:
            type: string
            format: date
          until:
            type: string
            format: date
          properties:
            type: object
            patternProperties:
              "^[a-zA-Z_]+$":
                type: object
                title: Data field
                properties:
                  type:
                    enum:
                      - string
                      - integer
                      - numeric
                  since:
                    type: string
                    format: date
                  until:
                    type: string
                    format: date
                required:
                  - type
            additionalProperties: false
        additionalProperties: false
    additionalProperties: false
required:
  - id
  - type
  - title
  - since
additionalProperties: false
definitions:
  impact:
    type: object
    properties:
      year:
        type: integer
        title: Year
      users:
        type: integer
        title: Number of users
        description: >
          Number of unique project users for a specified year.
      revenue:
        type: number
        title: Revenue in Euros
        description:
          Revenue in Eruos generated for a specified year.
      employees:
        type: integer
        title: Number of emplyees
        description:
          Number of emplyees, employed for specified year who worked on this
          project.
    additionalProperties: false
