---
$schema: http://atviriduomenys.lt/schama/project
$id: http://atviriduomenys.lt/schema/project.json
title: Data needed for a project
description: >
  Data description containing information about data needed for a project.
type: object
properties:
  id:
    type: string
    title: Project ID
    description: >
      Unique idetifier for a project withing a repository where all data
      descriptions are stored..
  title:
    type: string
    title: Project name
  type:
    enum:
      - project
  impact:
    type: array
    title: List of impact indicators by year
    items:
      type: object
      properties:
        year:
          type: integer
          title: Year
        users:
          type: integer
          title: Number of users
          description: >
            Number of unique project users for a specified year.
        revenue:
          type: float
          title: Revenue in Euros
          description:
            Revenue in Eruos generated for a specified year.
        employees:
          type: integer
          title: Number of emplyees
          description:
            Number of emplyees, employed for specified year who worked on this
            project.
  objects:
    $ref: http://atviriduomenys.lt/schema/data.json
