properties:
  sql:
    type: object
    properties:
      query:
        type: string
        description: >
          See: https://docs.sqlalchemy.org/en/latest/core/engines.html#database-urls
      encoding:
        type: string
